name: 🐛 Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Run command '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What you expected to happen
      placeholder: Describe what should happen...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened
      placeholder: Describe what actually happened...
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (blocks all work)
        - High (major feature broken)
        - Medium (workaround exists)
        - Low (minor issue)
    validations:
      required: true

  - type: textarea
    id: proposed-fix
    attributes:
      label: Proposed Fix
      description: If you have ideas on how to fix this, share them here
      placeholder: Optional - your thoughts on how to fix this...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Your environment details
      placeholder: |
        - OS: [e.g., macOS, Linux, Windows]
        - Node version: [e.g., 18.x]
        - Docker version: [e.g., 24.x]
      value: |
        - OS: 
        - Node version: 
        - Docker version: 

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, logs, or screenshots
      placeholder: Paste logs or add screenshots...
